export default {
  valid: [
    {
      id: 39,
      name: 'Centro de Fotografia de Montevideo',
      capacity: 20,
      distance: 94,
      latitude: -34.905759,
      longitude: -56.197307,
      numBikesAvailable: 10,
      numDocksAvailable: 10,
    },
    {
      id: 20,
      name: 'National Art Museum of China',
      capacity: 20,
      distance: 1700,
      latitude: 39.926532,
      longitude: 116.409167,
      numBikesAvailable: 10,
      numDocksAvailable: 10,
    },
  ],
  invalid: [
    {
      id: 10,
      name: 'Who knows',
      capacity: 20,
      latitude: null,
      longitude: -50.197307,
      numBikesAvailable: 10,
      numDocksAvailable: 10,
    },
    {
      id: 22,
      name: 'No information either',
      capacity: 20,
      distance: 94,
      latitude: null,
      longitude: null,
      numBikesAvailable: 10,
      numDocksAvailable: 10,
    },
  ],
  noBikesOrSpaces: [
    {
      capacity: 20,
      id: 3,
      latitude: 112.2,
      longitude: 3.43,
      name: 'No Bikes available here sorry mate',
      numBikesAvailable: 0,
      numDocksAvailable: 20,
      status: 'IN_SERVICE',
    },
    {
      capacity: 20,
      id: 19,
      latitude: 119.2,
      longitude: 9.42,
      name: 'No Spaces available here sorry mate',
      numBikesAvailable: 20,
      numDocksAvailable: 0,
      status: 'IN_SERVICE',
    },
  ],
};
